// Generated by Wrangler by running `wrangler types`

interface Env {
	SUPABASE_URL: "https://ngtpsrvaoimcuagsjpzy.supabase.co";
	SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ndHBzcnZhb2ltY3VhZ3NqcHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEyNjU0MjMsImV4cCI6MjA0Njg0MTQyM30.0_CZc-U6NKkRMqSQcskluofzzGZGRDGAoKm5_uHRocs";
}
